### ISSUE TITLE
what is the difference? and how to install from source on arch based os ?

### ISSUE THREAD

**Issue by saikatm** [HRex39/rtl8852be#13]
what is the difference between this repo and [this](https://github.com/lwfinger/rtw8852be/ ) ??

I used https://github.com/lwfinger/rtw8852be/ which worked fine on Pop! OS.
however, I can't install it on manjaro. can you tell me how to install the driver from the repo on an arch-based os like manjaro??

**Comment by HRex39** [comment]
My understanding is that Mr. lwfinger only adapted to 5.18 and newer kernels.  
My repo is supposed to be adapted by all versions of the kernel currently (5.19 I don't know), but the code is rough and not very elegant.
You can use command ```uname -r``` to check your kernel version and choose the branch.

**Comment by HRex39** [comment]
Different versions of the kernel have different APIs, and it's not clear whether lwfinger adapts to older kernels.

**Comment by saikatm** [comment]
sir can you tell me what is the procedure to install the driver on arch based OS like manjaro ?? I am a linux newbie. the make commands returns error...

**Comment by HRex39** [comment]
What kind of error please?
maybe the linux-headers?
please leave your error msg .
try:  
```
$ sudo pacman -S linux-headers
```

**Comment by saikatm** [comment]
i installed the right linux header version and the error did not happen.. but I don't know what to do as manjaro will get frequent kernel updates so the driver will break?

**Comment by HRex39** [comment]
When kernel updates， it's time for you to recompile the code.
Neither do I know what time will the code break， if it does break，you can open a new issue and report your condition.🙏

**Comment by HRex39** [comment]
You can use “LTS kernel” in manjaro instead of “Beta kernel”. Then I think the problem will show up more slowly.
