### ISSUE TITLE
Doesn't work on kernel version 5.18.16

### ISSUE THREAD

**Issue by nestlecrunchkid** [HRex39/rtl8852be#14]
Doesn't work on kernel version 5.18.16, and neither does LWFinger's.

**Comment by HRex39** [comment]
Please give some more detailed info like make problems or sth else.

**Comment by nestlecrunchkid** [comment]
https://user-images.githubusercontent.com/81821226/183391062-5aecb7e4-3b83-4006-bf64-834ed3699a9b.mp4

**Comment by HRex39** [comment]
What is your branch exactly?

**Comment by nestlecrunchkid** [comment]
> What is your branch exactly?

Main

**Comment by HRex39** [comment]
ReRead the README again please.
And if there is still a make problem, please paste the error msg.

**Comment by nestlecrunchkid** [comment]
Retryed with the other branch. No error messages, but modprobe does nothing.

**Comment by IanGe2000** [comment]
> Retryed with the other branch. No error messages, but modprobe does nothing.

I can confirm that modprobe gives no output. Have you tested the wifi connection?

**Comment by nestlecrunchkid** [comment]
> > Retryed with the other branch. No error messages, but modprobe does nothing.
> 
> I can confirm that modprobe gives no output. Have you tested the wifi connection?

Yes (I think). What exactly do you mean by testing the wifi connection?

**Comment by HRex39** [comment]
If make command return no error msg, have you make install it?
If you do so and wifi not connected, What's your Security Boot's status?

**Comment by HRex39** [comment]
Before committing your issue, please detailed describe your problems, otherwise you will not get any of answer you want.

**Comment by IanGe2000** [comment]
> > > Retryed with the other branch. No error messages, but modprobe does nothing.
> > 
> > 
> > I can confirm that modprobe gives no output. Have you tested the wifi connection?
> 
> Yes (I think). What exactly do you mean by testing the wifi connection?

This repo provides a Linux driver for rtl8852be, so I assume you need this for wifi connections. If you get wifi connections then it's working.

**Comment by nestlecrunchkid** [comment]
> > > > Retryed with the other branch. No error messages, but modprobe does nothing.
> > > 
> > > 
> > > I can confirm that modprobe gives no output. Have you tested the wifi connection?
> > 
> > 
> > Yes (I think). What exactly do you mean by testing the wifi connection?
> 
> This repo provides a Linux driver for rtl8852be, so I assume you need this for wifi connections. If you get wifi connections then it's working.

Then it's not working.

**Comment by nestlecrunchkid** [comment]
LWFinger's now works for me. IDK about this repo.

**Comment by HRex39** [comment]
hal_mem_cpy may cause the problem. I have tried to fix it according to LWFinger's issue, it's a good news to hear that you have solved your problem.
