### ISSUE TITLE
modprobe: ERROR: could not insert '8852be': Invalid argument

### ISSUE THREAD

**Issue by hpc4you** [HRex39/rtl8852be#15]
I have a laptop with Ryzen 6800H CPU. 
The keyboard fails to work, but fixed according to https://lore.kernel.org/all/20220712020058.90374-1-gch981213@gmail.com/ .  Patched **/drivers/acpi/resource.c** file. Then recompiled the kernel according to https://wiki.ubuntu.com/Kernel/BuildYourOwnKernel. The kernel version is 5.15.0-46.49. 
Now, the keyboard works as expected. 

The compile of rtl8852be driver passed with no errors.  
But fails to load into the kernel. 

> modprobe: ERROR: could not insert '8852be': Invalid argument

Not sure why. 

With the original kernel from Ubuntu, the  rtl8852be driver compiles and loads successfully.

**Comment by nestlecrunchkid** [comment]
Please post any make errors or other errors. I noticed that the modprobe worked after the make and sudo make install. During those steps, I was taken to a sub-directory of rtl8852be. Modprobe worked there, but not in the original rtl8852be directory. I forgot what directory I was taken to though...

**Comment by hpc4you** [comment]
OS: Ubuntu 22.04.1
Kernel: 5.15.0-46.49
CPU: R 6800H
Security Boot, disabled. 

How do I build the driver? 
```
sudo -i
git clone https://github.com/HRex39/rtl8852be.git
cd rtl8852be
make -j8  # warnings, no error. 
make install
modprobe 8852be
```
The driver works with the original kernel (5.15.0-46.49-generic) from Ubuntu 22.04.1 LTS (Jammy Jellyfish). The WiFi works. 

While, with this particular hardware, the keyboard does not work. 
According to https://lore.kernel.org/all/20220712020058.90374-1-gch981213@gmail.com/, patch /drivers/acpi/resource.c file, recompile the kernel, results in a functional keyboard, but WiFi fails. 

Recompile WiFi driver, 
```
sudo -i
cd rtl8852be
make uninstall
make clean 
make -j8
make install # warnings, no error. 
modprobe 8852be # Report error, modprobe: ERROR: could not insert '8852be': Invalid argument
```

With the original kernel, `modprobe 8852be` works. 
After patch /drivers/acpi/resource.c file, `modprobe 8852be` fails. 

> Please post any make errors or other errors. I noticed that the modprobe worked after the make and sudo make install. During those steps, I was taken to a sub-directory of rtl8852be. Modprobe worked there, but not in the original rtl8852be directory. I forgot what directory I was taken to though...

**Comment by hpc4you** [comment]
Update. 
Now `modprobe 8852be` works. 

Here is what I have done. 

Use the kernel source code from https://www.kernel.org/. 
In the current case, I selected 5.15.60. 

According to https://lore.kernel.org/all/20220712020058.90374-1-gch981213@gmail.com/, patch /drivers/acpi/resource.c file, recompile the kernel, to make the keyboard working...

```
sudo -i
cd rtl8852be
make uninstall
make clean 
make  # Caution, do not use make -j or something alike. 
make install
modprobe 8852be 
```

As I have mentioned above, though `make -j` runs a bit faster, `modprobe` will fail. Not sure why. 

The good news is, that both the keyboard and WiFi are working...
